[workspace]
resolver = "2"
members = [
    "libffi-rs",
    "libffi-sys-rs",
]

[workspace.package]
repository = "https://github.com/tov/libffi-rs"
license = "MIT/Apache-2.0"
keywords = ["ffi", "libffi", "closure", "c"]
edition = "2021"
rust-version = "1.78"
