//! Stable-Rust cleanup of the C2Rust output for `closures.c`.
//! Linux/powerpc64 configured static trampolines are deliberately declined;
//! libffi then uses the in-closure ELFv2 trampoline generated by ffi_linux64.
use core::ffi::{c_int, c_void};

type size_t = usize;
const PROT_READ: c_int = 1;
const PROT_WRITE: c_int = 2;
const PROT_EXEC: c_int = 4;
const MAP_PRIVATE: c_int = 2;
const MAP_ANONYMOUS: c_int = 0x20;
const MAP_FAILED: *mut c_void = usize::MAX as *mut c_void;
const MAP_GRANULE: usize = 64 * 1024;

#[repr(C, align(16))]
struct AllocationHeader {
    base: *mut c_void,
    len: usize,
}

extern "C" {
    fn mmap(
        addr: *mut c_void,
        len: usize,
        prot: c_int,
        flags: c_int,
        fd: c_int,
        offset: isize,
    ) -> *mut c_void;
    fn munmap(addr: *mut c_void, len: usize) -> c_int;
}

#[no_mangle]
pub unsafe extern "C" fn ffi_closure_alloc(size: size_t, code: *mut *mut c_void) -> *mut c_void {
    let need = match size.checked_add(core::mem::size_of::<AllocationHeader>()) {
        Some(n) => n,
        None => return core::ptr::null_mut(),
    };
    let len = match need.checked_add(MAP_GRANULE - 1) {
        Some(n) => n & !(MAP_GRANULE - 1),
        None => return core::ptr::null_mut(),
    };
    let base = mmap(
        core::ptr::null_mut(),
        len,
        PROT_READ | PROT_WRITE | PROT_EXEC,
        MAP_PRIVATE | MAP_ANONYMOUS,
        -1,
        0,
    );
    if base == MAP_FAILED {
        return core::ptr::null_mut();
    }
    let header = base.cast::<AllocationHeader>();
    header.write(AllocationHeader { base, len });
    let data = header.add(1).cast::<c_void>();
    if !code.is_null() {
        code.write(data);
    }
    data
}

#[no_mangle]
pub unsafe extern "C" fn ffi_closure_free(ptr: *mut c_void) {
    if ptr.is_null() {
        return;
    }
    let header = ptr.cast::<AllocationHeader>().sub(1);
    let saved = header.read();
    let _ = munmap(saved.base, saved.len);
}

#[no_mangle]
pub unsafe extern "C" fn ffi_data_to_code_pointer(data: *mut c_void) -> *mut c_void {
    data
}
#[no_mangle]
pub unsafe extern "C" fn ffi_tramp_is_present(_ptr: *mut c_void) -> c_int {
    0
}
#[no_mangle]
pub unsafe extern "C" fn open_temp_exec_file() -> c_int {
    -1
}
